// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/__copypatch/api/v2/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/__copypatch/api/v2/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/copypatch-api.ts": {
    id: "routes/copypatch-api";
    page: "/__copypatch/api/v2/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/copypatch-api": typeof import("./app/./routes/copypatch-api.ts");
};